<template>
  <article class="report page-enter">
    <div class="report-toolbar"><span class="eyebrow">PERSONAL REPORT / {{ results.evaluatedAt }}</span><button class="text-button" @click="$emit('edit')">修改回答</button></div>
    <section class="report-hero">
      <div class="hero-copy"><span class="hero-kicker">关于这份工作，想和你说几句</span><p class="report-company">{{ results.companyName }}</p><h1>{{ results.strategy.label }}</h1><p>{{ results.summary }}</p><div class="hero-tags"><span>{{ results.focus ? '最在意 · '+results.focus.name : '工作状态 · 相对稳定' }}</span><span>{{ results.readiness.some(r=>r.score<40)?'想走之前 · 还要准备一下':'想走之前 · 再看看具体机会' }}</span></div></div>
      <div class="hero-note"><span>YOUR NEXT CHAPTER</span><b>去或留，<br>都有自己的<br><em>节奏。</em></b><span>看清现状，再往前一步。</span></div>
    </section>
    <nav class="report-nav" aria-label="报告章节"><a href="#work">01 工作状态</a><a href="#readiness">02 离职准备</a><a href="#plan">03 行动计划</a></nav>
    <section v-if="results.alerts.length" class="alert-section" aria-labelledby="alert-title"><div class="section-kicker">先读这一部分</div><h2 id="alert-title">这几件事，先别一个人扛</h2><div v-for="alert in results.alerts" :key="alert.id" class="alert-item"><h3>{{ alert.title }}</h3><p class="evidence">你选择了：“{{ alert.answer }}”</p><p>{{ alert.description }}</p><button class="text-button" @click="$emit('edit',alert.questionId)">核对这项回答</button></div></section>
    <section id="work" class="report-section"><div class="section-heading"><div><span class="section-kicker">01 / UNDERSTAND YOUR WORK</span><h2>这份工作，正在如何影响你</h2></div><span class="direction-note">所有维度：分数越高，状态越好</span></div>
      <div class="work-grid"><div class="paper dimension-list"><div v-for="dim in results.dimensions" :key="dim.id" class="dimension-row"><div class="dimension-title"><h3>{{ dim.name }}</h3><div><span :class="['status',dim.tone]">{{ dim.label }}</span><b>{{ dim.score }}<small>/100</small></b></div></div><div class="score-track" role="meter" :aria-label="dim.name" :aria-valuenow="dim.score" aria-valuemin="0" aria-valuemax="100"><span :class="dim.tone" :style="{width:dim.score+'%'}"></span></div><p class="dimension-description">{{ dim.description }}</p><details><summary>为什么这样说？</summary><p>你选择了：“{{ dim.evidence.answer }}”</p><button class="text-button" @click="$emit('edit',dim.evidence.questionId)">修改这项回答</button></details></div></div>
        <aside class="paper radar-card"><span class="section-kicker">工作状态概览</span><RadarChart :data="results.radarData"/><div class="strength-note"><span class="small muted">值得保留的部分</span><h3>{{ results.strengths.length ? results.strengths.map(d=>d.name).join(' · ') : '目前没有明显优势项' }}</h3><p class="small muted">{{ results.strengths.length?'这些是你对当前工作比较满意的地方。以后看机会时，也可以记着：哪些好处，你还想继续拥有。':'这次回答里，还没有哪一项让你特别满意。不用勉强给这份工作找优点，先照顾眼下最困扰你的事。' }}</p></div></aside>
      </div>
    </section>
    <section id="readiness" class="report-section"><div class="section-heading"><div><span class="section-kicker">02 / MAKE ROOM FOR CHANGE</span><h2>真要走了，钱、机会和精力够不够</h2></div></div><p class="section-intro">钱够不够花、有没有机会、自己还有没有精力，分开看看会更清楚。准备程度越高，说明这一项越有底。</p><div class="readiness-grid"><div v-for="(item,i) in results.readiness" :key="item.id" class="paper readiness-card"><span class="readiness-number">0{{ i+1 }}</span><div class="readiness-title"><h3>{{ item.name }}</h3><span :class="['status',item.tone]">{{ item.label }}</span></div><p>{{ item.detail }}</p><button class="text-button" @click="$emit('edit',item.questionId)">核对回答</button></div></div><div class="constraint-note"><b>有几句实在话，想提醒你</b><p v-for="line in results.constraints" :key="line">{{ line }}</p></div></section>
    <section id="plan" class="report-section"><div class="section-heading"><div><span class="section-kicker">03 / YOUR NEXT 30 DAYS</span><h2>接下来，先做这几件小事</h2></div><span class="completion">{{ checked.length }} / {{ results.actions.length }} 已完成</span></div><p class="section-intro">{{ results.strategy.description }} 不用一天做完，接下来一个月慢慢来。</p><p v-if="results.pacing" class="section-intro">{{ results.pacing }}</p><div class="action-list"><section v-for="(action,i) in results.actions" :key="action.id" class="paper action-card" :class="{'is-done':checked.includes(action.id)}"><div class="action-index">{{ String(i+1).padStart(2,'0') }}</div><div class="action-content"><div class="section-kicker">{{ action.when }}</div><h3>{{ action.title }}</h3><p class="action-evidence">因为你提到过：“{{ action.evidence }}”</p><p>{{ action.task }}</p><div v-if="action.starter" class="review-trigger"><span>不知道怎么开口？可以这样说</span><p>{{ action.starter }}</p></div><div class="review-trigger"><span>过段时间，再看看</span><p>{{ action.review }}</p></div><label class="check-action"><input type="checkbox" :checked="checked.includes(action.id)" @change="$emit('toggle-action',action.id)"><span>{{ checked.includes(action.id)?'这一步，做到了':'做到了，打个勾' }}</span></label></div></section></div></section>
    <section class="paper report-method"><details><summary>分数与建议是怎样产生的？</summary><p>工作状态按四个维度分别计算：将所选选项的风险分相加，再除以该维度最高可能分数，最后反向换算为 0—100 分。70—100 分为相对稳定，40—69 分为有待改善，0—39 分为优先关注。这些是内部展示阈值，没有常模或临床诊断含义。</p><p>策略参考身心 30%、团队 25%、回报 25%、成长 20% 的内部风险权重；单项突出问题及特别关注回答单独处理。离职准备按三道题分别展示，不与工作状态合成“离职概率”。</p><p>行动优先匹配严重程度较高的具体回答，并结合生活缓冲、求职机会与精力调整内容。这里提供的是自我梳理建议，不替代个人判断或医学、法律等专业服务。</p></details></section>
    <section class="report-export"><div><h3>先存下来，想不清的时候再翻翻。</h3><p class="small muted">完整报告可打印为 PDF；分享卡默认隐藏工作名称。</p></div><div class="export-buttons"><button class="secondary" @click="copyPlan">复制计划</button><button class="secondary" @click="printReport">保存完整报告</button><button class="primary" @click="$emit('share')">生成分享卡 ↗</button></div></section>
    <p class="print-footer">去留 · 个人职业决策手册 / {{ results.evaluatedAt }} · 自评参考，不代表离职概率或专业诊断。</p>
  </article>
</template>
<script setup>
import { onMounted, onUnmounted } from 'vue'
import RadarChart from './RadarChart.vue'
const props=defineProps({results:Object,checked:{type:Array,default:()=>[]}})
const emit=defineEmits(['edit','toggle-action','share','notice'])
let openedForPrint=[]
const expandForPrint=()=>{openedForPrint=[...document.querySelectorAll('.report details:not([open])')];openedForPrint.forEach(el=>el.open=true)}
const restoreAfterPrint=()=>{openedForPrint.forEach(el=>el.open=false);openedForPrint=[]}
onMounted(()=>{window.addEventListener('beforeprint',expandForPrint);window.addEventListener('afterprint',restoreAfterPrint)})
onUnmounted(()=>{window.removeEventListener('beforeprint',expandForPrint);window.removeEventListener('afterprint',restoreAfterPrint)})
const printReport=()=>window.print()
const copyPlan=async()=>{const text=[`去留 · ${props.results.companyName}`,props.results.evaluatedAt,props.results.strategy.label,props.results.summary,props.results.pacing||'','',...props.results.actions.map((a,i)=>`${i+1}. ${a.title}\n你提到：${a.evidence}\n行动：${a.task}${a.starter ? `\n可以这样说：${a.starter}` : ''}\n过段时间再看看：${a.review}`),'','自评参考，按实际情况调整。'].join('\n');try{await navigator.clipboard.writeText(text);emit('notice','行动计划已复制')}catch{emit('notice','浏览器未允许复制，请使用“保存完整报告”。')}}
</script>
